### ISSUE TITLE
Increase Performance

### ISSUE THREAD

**Issue by cyacedev** [ViewTube/viewtube#71]
### description
This issue holds any discussion related to possible performance increases

### To-Do's
- [ ] Research tools to check for performance problems
- [ ] Possibility to decrease file size (for docker and transmit to client)
- [x] Split routes into webpack chunks 
- [x] Don't include devDependencies in docker image
- [x] Switch to faster proxy

**Comment by cyacedev** [comment]
For UI Profiling, Lighthouse and vue-perf-devtools could be used.
Any kind of research is appreciated, if a specific improvement is found, please create a new issue and reference this one.

**Comment by mizzunet** [comment]
It seems like for now, dev.viewtube.io is faster on loading videos than viewtube.io
